spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 5738eba2b7b240e9e1e4ebda45952c29 # RestApi키
            client-secret: AYoCy7L8deMzLy6yq3IFLJ5RX0aNmuEa # 보안키
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname,profile_image, account_email
            client-name: kakao
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.ocm/v2/user/me
            user-name-attribute: id
  datasource:
    url: jdbc:mysql://localhost:3306/db_ajoutee?serverTimezone=Asia/Seoul
    username: jju
    password: 30501
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션
  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: trace

secret-key:
  bus: "LptPwU%2BeOglSoKJ6cOGTry0zs4NMSpnGFCLKNYusbmV7QbNNrFEfunRev8%2B2%2BGM2CiqNOp24cYhFpNusF1dg8A%3D%3D"

fcm:
  service-account-file: key/serviceAccount.json
  topic-name: testMessage
  project-id: igottago-1c5f5

logging:
  level:
    root: info
jwt:
  secret: "Z29nby10bS1zZXJ2ZXItZGxyamVvYW9ydsfsdfrtdG9kZ6764364afgtduaW0teWVFGDGARWpaGFsZ2VveW8K"


